apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong-deployment
spec:
  selector:
    matchLabels:
      app: pong
  template:
    metadata:
      labels:
        app: pong
    spec:
      containers:
        - name: pong
          image: gcr.io/pong-297810/pong-docker
          ports:
            - containerPort: 3000
